global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "bundlefabric"
    static_configs:
      - targets: ["bundlefabric-api:8000"]
    metrics_path: /metrics
    scrape_interval: 15s
